version: "3.8"

services:
  foo:
    image: alpine
    deploy:
      mode: replicated
      replicas: 6
    command: ping localhost
    networks:
      - net
    volumes:
      - vol1:/tmp

networks:
  net:
    driver: overlay

volumes:
  vol1:
    driver: glusterfs
    name: "myvolume"

