version: "3.8"

networks:
  internal:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
    db_data:
    wp_data:

services:

  db:
    image: mariadb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 15s
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: ${CLIENT_ID}
        MYSQL_PASSWORD: ${CLIENT_ID}
        MYSQL_ROOT_PASSWORD: ${CLIENT_ID}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
 
  wp:
    image: wordpress:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 15s
      labels:
        - "traefik.enable=true"
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${CLIENT_ID}-wp-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${CLIENT_ID}-wp-http.entrypoints=http
        - traefik.http.routers.${CLIENT_ID}-wp-http.middlewares=https-redirect
        - traefik.http.routers.${CLIENT_ID}-wp-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.${CLIENT_ID}-wp-https.entrypoints=https
        - traefik.http.routers.${CLIENT_ID}-wp-https.tls=true
        - traefik.http.routers.${CLIENT_ID}-wp-https.tls.certresolver=le
        - traefik.http.services.${CLIENT_ID}-wp.loadbalancer.server.port=80
    environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: ${CLIENT_ID}
        WORDPRESS_DB_PASSWORD: ${CLIENT_ID}
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: wp_
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    networks:
      - internal
      - traefik-public 

