version: "3.3"

networks:
  internal:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

services:
  app:
    image: jpcordeiro/sigmasix
    command: 'php artisan serve --host=0.0.0.0'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 15s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.sigmasix-http.rule=Host(`${CLIENT_ID}.${DOMAIN?Variable not set}`)
        - traefik.http.routers.sigmasix-http.entrypoints=http
        - traefik.http.routers.sigmasix-http.service=sigmasix
        - traefik.http.routers.sigmasix-http.middlewares=https-redirect
        - traefik.http.routers.sigmasix-https.rule=Host(`${CLIENT_ID}.${DOMAIN?Variable not set}`)
        - traefik.http.routers.sigmasix-https.entrypoints=https
        - traefik.http.routers.sigmasix-https.service=sigmasix
        - traefik.http.routers.sigmasix-https.tls=true
        - traefik.http.routers.sigmasix-https.tls.certresolver=le
        - traefik.http.services.sigmasix.loadbalancer.server.port=8000
    networks:
      - traefik-public

